services:
  nginx:
    container_name: nginx_container
    image: nginx:stable-alpine
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - backend
    depends_on:
      app:
        condition: service_started
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
    env_file:
      - ../.env
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    container_name: postgres_container
    image: postgres:15.5
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USER}
      PGDATA: /data/postgres
    volumes:
      - app_postgres_vol:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 2s
      timeout: 5s
      retries: 50
  redis:
    container_name: redis_container
    image: redis:7.2.4-alpine3.19
    restart: always
    env_file:
      - ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - app_redis_vol:/var/lib/redis/data
      - app_redis_config_vol:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - backend
    command: >
      --requirepass ${REDIS_PASSWORD}

networks:
  backend:

volumes:
  app_postgres_vol:
  app_redis_vol:
  app_redis_config_vol:
